### ISSUE TITLE
Motor speeds are too low

### ISSUE THREAD

**Issue by tcorbly** [kipr/Simulator#130]
When running a command like mav or mtp, it should be expected that the motors will turn at a rate of 1500 ticks/s at full speed. Using the code below we can determine the rate is about 650 ticks/s currently at max speed instead, reaching around 2600 ticks over 4 seconds.

```c
#include <stdio.h>
#include <kipr/wombat.h>

int main()
{
  cmpc(0);
  mtp(0, 1500, 3000);
  msleep(4000L);
  return 0;
}
```

**Comment by navzam** [comment]
From discussion on Discord, we figured out this was an inconsistency between machines due to the use of fixed time steps for physics.
