### ISSUE TITLE
Reset button doesn't work if the robot moved without user input

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#167]
~The reset button to reset the robot position is missing from the new UI.~ The reset button exists, but it doesn't work if the robot drives somewhere without user input. It only works if the robot was moved by entering positions in the position box.

**Comment by tcorbly** [comment]
It should be there right above the positions

**Comment by navzam** [comment]
Ah sorry, didn't see that. I'll retitle for the issue you mentioned.
