### ISSUE TITLE
Detect when user program ends

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#176]
Currently the user has to click "Stop" after their program is done running. It'd be nice if we could detect when the program finishes and set the UI state accordingly.

It might be tricky to know when the program ends through emscripten, especially since we're keeping the emscripten runtime alive. We could insert some code after `main()` is done, but that would only work if the program terminates cleanly.

**Comment by tcorbly** [comment]
I would say this is more of a bug at this point and would promote it to high. Run still remains grayed out.
