### ISSUE TITLE
Add an easy way for people to submit issues/feedback

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#201]
We should have some way for people to submit issues/feedback directly from the simulator, or at least instruct people on how to submit them externally. Some ideas:

- In the About dialog, direct people to the GitHub issues page if they have a GitHub account, or provide a KIPR email address otherwise.
- In a separate Feedback dialog, allow users to enter their feedback and optionally their email address. Our backend could then send an email to a KIPR email address, or directly post the issue on GitHub

For bonus points, capture the user's sentiment (smiley face, neutral face, frowny face), user's browser info, current code, or any other info that would be useful for debugging issues.

**Comment by will-jac** [comment]
Starting work on a dedicated Feedback dialog that lives in the main menu.

Eventually, the feedback might go to a database, where a microservice could automatically post it to a channel in discord

**Comment by navzam** [comment]
Resolved by #292 and #295
