### ISSUE TITLE
Sensor values do not update multiple times throughout program. Test with code below.

### ISSUE THREAD

**Issue by tcorbly** [kipr/Simulator#23]
#include <stdio.h>
#include <kipr/wombat.h>

int main()
{
  printf("Hello, Sensors! %d\n", analog(0));
  motor(0,50);
  motor(3,50);
  msleep(3000);
  ao();
  printf("Goodbye, Sensors! %d\n", analog(0));
  return 0;
}

**Comment by navzam** [comment]
@tcorbly When I run that code (with Simulator on branch `master` and libwallaby on branch `emscripten-read-register-sleep`), the robot moves forward into the green box and I get this output:

```
Hello, Sensors! 52
Goodbye, Sensors! 117
```

which seems reasonable to me. Are you sure you're on the correct branch of libwallaby? If so, what output are you seeing?
