### ISSUE TITLE
Inline Documentation Viewer

### ISSUE THREAD

**Issue by bmcdorman** [kipr/Simulator#242]
Currently the "Documentation" button on the menu takes you to the doxygen website. It'd be cool if this information was presented in a widget of some sort (to not break the user from the simulator context) and richly tied to ivygate (e.g., clicking on a function in the editor could pop open the doc viewer.

There are a few ways to approach this, but I propose the following pipeline: Doxygen XML -> JSON -> custom React components.

Fortunately for you, dear reader, I have already created [a set of high quality React components and a Doxygen XML processing pipeline](https://github.com/drydoc-org/drydoc) for documentation under a permissive license that exactly matches Simulator's software stack.

**Comment by navzam** [comment]
Resolved in #451 #452 and #453
