### ISSUE TITLE
Better iPad support

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#262]
Some iPad issues that have been brought up:
- ~Simulator area is not fullscreen~ (fixed)
- ~No way to scroll the panels~ (fixed)

The main thing remaining is proper touch support for both the UI and simulator area.

**Comment by tcorbly** [comment]
The simulator area issue also occurs no matter which browser is used on an iPad.

**Comment by tcorbly** [comment]
Marking as closed since all issues were addressed.
