### ISSUE TITLE
Issue with CMPC and GMPC

### ISSUE THREAD

**Issue by headbotguy** [kipr/Simulator#282]
If I am using cmpc and then a loop with gmpc to make a turn, it only runs one time and will not run again unless I refresh the simulator. The scale is way off as well compared to the actual robot.

cmpc(3);
while (gmpc (3) < 1800)
{
motor (0,1);
motor (3,50);
}

**Comment by tcorbly** [comment]
After some testing, this appears to be an issue with motor 3. If you try replacing the calls with 0 instead of 3 it works.

**Comment by headbotguy** [comment]
Ok so Mac only works on port 0, good to know

**Comment by tcorbly** [comment]
It's on Windows as well. All my test programs usually use port 0 so that's why yours caught it.

**Comment by headbotguy** [comment]
Instead of Mac it should have said MPC 😂
