### ISSUE TITLE
Hiding options for "Robot" and "World" windows.

### ISSUE THREAD

**Issue by headbotguy** [kipr/Simulator#283]
For our beginners and younger students that may be overwhelmed by so many options. Can we put all of the options in these two windows under a dropdown menu or make an option settings where you can select to see all of them (as you do now) or hide all but the title of the two windows?

**Comment by navzam** [comment]
I think this is resolved by the side layout (#343), especially now that it's the default layout (#401) . Feel free to reopen if needed
