### ISSUE TITLE
Allow full screen on embedded YouTube videos

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#303]
On the tutorials page, the full screen button on the embedded YouTube videos is disabled. We should see if it's possible to enable full screen. It might be an attribute on the `iframe`.

**Comment by Melanieann11786** [comment]
![received_257077159885055](https://user-images.githubusercontent.com/97970600/150666654-439bf7d6-0547-4d1d-bda0-55fccd4d2df7.jpeg)

**Comment by Melanieann11786** [comment]
My husband has the biggest dick ever he is fucking me in the ass tonight this is gonna hurt
