### ISSUE TITLE
Add loading indicator when scene is loading

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#311]
When the simulator is first loading, the 3D area is gray until the scene loads and renders. Especially on first use, this load can take some time, so we should show some kind of loading indicator to tell the user that things are happening.

**Comment by will-jac** [comment]
Is this for the scene specifically or to replace the white 'Loading' screen (which says loading in the top left in small font, and nothing else?

**Comment by navzam** [comment]
I was referring to the scene specifically, but the small 'Loading' text would be good to replace too

**Comment by will-jac** [comment]
I'll open an issue for it
