### ISSUE TITLE
Zooming in/out in the canvas causes the whole page to scroll up/down

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#35]
Scrolling in the 3D area (to make the camera zoom in and out) also causes the whole page to scroll. Scroll events in the 3D area shouldn't affect the rest of the page.

**Comment by tcorbly** [comment]
I believe when Braden pushes the new UI this should be fixed.

**Comment by navzam** [comment]
No longer an issue in the new UI (#157)
