### ISSUE TITLE
FPS decreases significantly when printing large amounts to console

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#358]
Performance decreases significantly when there's a large amount of text being printed to the console quickly. Example program:

```c
#include <stdio.h>
#include <kipr/wombat.h>

int main()
{
  for (int i = 0; i < 500; ++i)
  {
    printf("Hello, World %d\n", i);
    msleep(10L);
  }
  return 0;
}

```

While the code above runs, the simulator runs a lot slower. After the code finishes running, performance returns to normal. It's especially apparent if run multiple times without clearing the console.

Marking as high priority because I think this kind of tight printing loop is commonly used in Botball.

**Comment by bmcdorman** [comment]
Fixed by #406
