### ISSUE TITLE
Ordering of items in World panel seems random/dynamic

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#449]
The order of the items in the World panel seems random and changes each time you open the world. It can change even if you don't reopen the world.

Repro:
1. Create a new custom world (or open one that already exists)
2. Open the World side panel and note the ordering of the items
3. Click `World -> Open` and then close the dialog
4. Notice the ordering of the items has changed

**Comment by tcorbly** [comment]
I believe this is fixed as of the 2.0.0 update.
