### ISSUE TITLE
Issues loading on iPad

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#47]
Some iPad users have issues with the simulator not loading/displaying. @tcorbly brought this up and may have more details.

**Comment by tcorbly** [comment]
Unsure of the issue with the 3D but generally iPads and probably iPhone as well are not loading any of the images that are being used in the 2D simulator. This includes the KIPR logo that is in the top left.

**Comment by tcorbly** [comment]
Still unsure on why the issue pops up but updating my iPad caused the issue to go away so hopefully that ends up being the fix. It definitely is an iOS specific issue though.
