### ISSUE TITLE
Reset button doesn't reset robot's position

### ISSUE THREAD

**Issue by navzam** [kipr/Simulator#54]
Clicking "reset" doesn't reset the position of the robot. This was likely left over from the 2D simulator and needs to be rewritten for the 3D version.

**Comment by tcorbly** [comment]
Yes in general setting the robot's position in the 3D simulator needs to be figured out.

**Comment by navzam** [comment]
Yeah. I think positioning in general will be easier once we resolve #46 and have better parenting for the model.
