### ISSUE TITLE
mtp does not stop at position

### ISSUE THREAD

**Issue by tcorbly** [kipr/Simulator#8]
move_to_position does not stop at specified position and continues when msleep is longer than period needed to get to position

**Comment by prithvirajkadiyala** [comment]
This is still being worked on. Apparently the program doesn't respond with the correct value back to the code, so that the robot can stop when the desired position is achieved.

**Comment by navzam** [comment]
I'm working on this as part of getting all the common motor commands working, including `mrp()`/`mtp()` and the position functions like `gmpc()`/`cmpc()`
