### ISSUE TITLE
Motor speeds not capped at 100%

### ISSUE THREAD

**Issue by tcorbly** [kipr/Simulator#88]
Motor speeds aren't capped at 100 which also causes unintentional sliding when they move too fast. Test at speeds of 500 or 1000 to replicate.

**Comment by navzam** [comment]
I feel like libwallaby should be responsible for capping, since it should probably be capped on controllers too. Should we open a libwallaby issue to go along with this?

Though it wouldn't hurt to add a check in the simulator too.
